# This file is machine-generated - editing it directly is not advised

[[AbstractAlgebra]]
deps = ["InteractiveUtils", "LinearAlgebra", "Markdown", "Random", "SparseArrays", "Test"]
git-tree-sha1 = "8fa03ecf25341ff3e8fb301dba3f41c6fe09952e"
uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
version = "0.10.0"

[[Antic_jll]]
deps = ["FLINT_jll", "GMP_jll", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "b4292ec817e615f208c4498fb6a56173b3aec7f9"
uuid = "e21ec000-9f72-519e-ba6d-10061e575a27"
version = "0.2.2+0"

[[Arb_jll]]
deps = ["FLINT_jll", "GMP_jll", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "46984472669a369e1a601df950a5b04bab8d7c00"
uuid = "d9960996-1013-53c9-9ba4-74a4155039c3"
version = "2.18.1+0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinaryProvider]]
deps = ["Libdl", "Logging", "SHA"]
git-tree-sha1 = "ecdec412a9abc8db54c0efc5548c64dfce072058"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.5.10"

[[CodeTracking]]
deps = ["InteractiveUtils", "UUIDs"]
git-tree-sha1 = "2884932d84a30e6873c49f97e939734329ac044b"
uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
version = "1.0.3"

[[CompilerSupportLibraries_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7c4f882c41faa72118841185afc58a2eb00ef612"
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "0.3.3+0"

[[CxxWrap]]
deps = ["Libdl", "MacroTools", "libcxxwrap_julia_jll"]
git-tree-sha1 = "762359626941f45b21238eb373a0bcedf6b61dd7"
uuid = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
version = "0.11.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DocStringExtensions]]
deps = ["LibGit2", "Markdown", "Pkg", "Test"]
git-tree-sha1 = "50ddf44c53698f5e784bbebb3f4b21c5807401b1"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.8.3"

[[FLINT_jll]]
deps = ["GMP_jll", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "4c6fd3affbb000d0890b0a67059a41c35bc6b829"
uuid = "e134572f-a0d5-539d-bddf-3cad8db41a82"
version = "2.6.3+0"

[[FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[GAP]]
deps = ["BinaryProvider", "Libdl", "Markdown", "Pkg", "REPL"]
git-tree-sha1 = "054716931de22333fb863fa65a67c5e8a38f4bd9"
uuid = "c863536a-3901-11e9-33e7-d5cd0df7b904"
version = "0.4.4"

[[GLPK_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "c0e1e14053ea92095daf648eeb2060150cfa6f34"
uuid = "e8aa6df9-e6ca-548a-97ff-1f85fc5b8b98"
version = "4.65.0+0"

[[GMP_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "4dd9301d3a027c05ec403e756ee7a60e3c367e5d"
uuid = "781609d7-10c4-51f6-84f2-b8444358ff6d"
version = "6.1.2+5"

[[Gettext_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "XML2_jll"]
git-tree-sha1 = "922315c1eb4e5072b9994fc47072d0351906fe4c"
uuid = "78b55507-aeef-58d4-861c-77aaff3498b1"
version = "0.20.1+6"

[[Hecke]]
deps = ["AbstractAlgebra", "Dates", "Distributed", "InteractiveUtils", "Libdl", "LinearAlgebra", "Markdown", "Nemo", "Pkg", "Printf", "Profile", "Random", "Requires", "Serialization", "SparseArrays", "Test"]
git-tree-sha1 = "371f42757d2f9a77030b1035badf7350c3d88f2c"
uuid = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
version = "0.8.5"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "81690084b6198a2e1da36fcfda16eeca9f9f24e4"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.1"

[[JuliaInterpreter]]
deps = ["CodeTracking", "InteractiveUtils", "Random", "UUIDs"]
git-tree-sha1 = "5b9b328eeea7bb85caca1576c15041e8faeb9041"
uuid = "aa1ae85d-cabe-5617-a682-6adf51b2e16a"
version = "0.8.1"

[[LZO_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "9d0c44be3e6d9690b19fa2cddb4c2e4b267ef425"
uuid = "dd4b983a-f0e5-5f8d-a1b7-129d4a5fb1ac"
version = "2.10.0+2"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[Libiconv_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "7c36dfe7971e55da03d8f54b67d4b3fb8ee01d63"
uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531"
version = "1.16.0+6"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[LoadFlint]]
deps = ["BinaryProvider", "FLINT_jll", "GMP_jll", "Libdl", "MPFR_jll", "Pkg"]
git-tree-sha1 = "4de92c7daa511ecbb38650004aaf6e16de72388d"
uuid = "472f376f-f1cf-461b-9ac1-d103423be9b7"
version = "0.3.3"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[LoweredCodeUtils]]
deps = ["JuliaInterpreter"]
git-tree-sha1 = "ab33e17d4f5f897a1f86da4e05138fff6c8dc85e"
uuid = "6f1432cf-f94c-5a45-995e-cdbf5db27b0b"
version = "1.2.1"

[[MPFR_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "301ce96952df90bbaa2c66112b7c1f15ced2b55b"
uuid = "3a97d323-0669-5f0c-9066-3539efd106a3"
version = "4.1.0+1"

[[MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "f7d2e3f654af75f01ec49be82c231c382214223a"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.5"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[MongoC_jll]]
deps = ["Libdl", "OpenSSL_jll", "Pkg", "Zlib_jll", "Zstd_jll", "snappy_jll"]
git-tree-sha1 = "714054676cf3ca277d5f0d28d79cc7795d9adbf8"
uuid = "90100e71-7732-535a-9be7-2e9affd1cfc1"
version = "1.16.2+0"

[[Mongoc]]
deps = ["Dates", "MongoC_jll", "Serialization"]
git-tree-sha1 = "d5b83f03ea94cafe6a7ed5440a8100beed569628"
uuid = "4fe8b98c-fc19-5c23-8ec2-168ff83495f2"
version = "0.6.1"

[[MozillaCACerts_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "95658ebdf17c9e2689905c8684abbbb5d85e3cff"
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"
version = "2020.7.22+0"

[[Ncurses_jll]]
deps = ["Gettext_jll", "Libdl", "Pkg"]
git-tree-sha1 = "8abe113efbf13dae7069194902f54aeb3c202e62"
uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
version = "6.1.0+4"

[[Nemo]]
deps = ["AbstractAlgebra", "Antic_jll", "Arb_jll", "BinaryProvider", "FLINT_jll", "InteractiveUtils", "Libdl", "LinearAlgebra", "LoadFlint", "Markdown", "Pkg", "Random", "Test"]
git-tree-sha1 = "c672975dab57391df030e7660d30e4c42e526edf"
uuid = "2edaba10-b0f1-5616-af89-8c11ac63239a"
version = "0.18.1"

[[Ninja_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "be987b7d4265f3297c8c5740bbc95fdeb6b5358e"
uuid = "76642167-d241-5cee-8c94-7a494e8cb7b7"
version = "1.10.0+0"

[[OpenSSL_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "997359379418d233767f926ea0c43f0e731735c0"
uuid = "458c3c95-2e84-50aa-8efc-19380b2a3a95"
version = "1.1.1+5"

[[OrderedCollections]]
git-tree-sha1 = "16c08bf5dba06609fe45e30860092d6fa41fde7b"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.3.1"

[[Oscar]]
deps = ["AbstractAlgebra", "DocStringExtensions", "GAP", "Hecke", "Markdown", "Nemo", "Pkg", "Polymake", "Requires", "Singular", "Test"]
git-tree-sha1 = "5d595e843a71df04da0e8027c4773a158be0c4f4"
uuid = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
version = "0.5.0"

[[PPL_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "4cb5b7f7b6ad18d8ff955bea75fca1ca650bf3e0"
uuid = "80dd9cbb-8b87-5171-a280-372cc418f402"
version = "1.2.0+0"

[[Parsers]]
deps = ["Dates", "Test"]
git-tree-sha1 = "8077624b3c450b15c087944363606a6ba12f925e"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "1.0.10"

[[Perl_jll]]
deps = ["Libdl", "Pkg", "Readline_jll"]
git-tree-sha1 = "52e12608bfaae678cb93f7e879d8a0828ca905da"
uuid = "83958c19-0796-5285-893e-a1267f8ec499"
version = "5.30.3+0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Polymake]]
deps = ["CxxWrap", "FLINT_jll", "JSON", "Libdl", "Markdown", "Mongoc", "MozillaCACerts_jll", "Ninja_jll", "Perl_jll", "Pkg", "REPL", "SparseArrays", "libpolymake_julia_jll", "polymake_jll"]
git-tree-sha1 = "2ff8a1c970a096d855c3c583130abdca04fe0f31"
uuid = "d720cf60-89b5-51f5-aff5-213f193123e7"
version = "0.5.0"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Profile]]
deps = ["Printf"]
uuid = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Readline_jll]]
deps = ["Libdl", "Ncurses_jll", "Pkg"]
git-tree-sha1 = "1efb93f0083416648dd8ab7702f52a0451a27c87"
uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
version = "8.0.4+0"

[[Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "28faf1c963ca1dc3ec87f166d92982e3c4a1f66d"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.1.0"

[[Revise]]
deps = ["CodeTracking", "Distributed", "FileWatching", "JuliaInterpreter", "LibGit2", "LoweredCodeUtils", "OrderedCollections", "Pkg", "REPL", "UUIDs", "Unicode"]
git-tree-sha1 = "3ac52e8b8c0140ba894c81ecac0f6a38987609ab"
uuid = "295af30f-e4ad-537b-8983-00126c2a3abe"
version = "3.1.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Singular]]
deps = ["AbstractAlgebra", "BinaryProvider", "CxxWrap", "GMP_jll", "Libdl", "LinearAlgebra", "MPFR_jll", "Markdown", "Nemo", "Pkg", "Singular_jll", "Statistics", "lib4ti2_jll", "libsingular_julia_jll"]
git-tree-sha1 = "53e2c31364f49ed05830e7e38001704d4d1b461b"
uuid = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
version = "0.4.1"

[[Singular_jll]]
deps = ["FLINT_jll", "GMP_jll", "Libdl", "MPFR_jll", "Pkg", "cddlib_jll"]
git-tree-sha1 = "fd64a8bf0ec47c4dd22806dd192798d1ad0ce487"
uuid = "43d676ae-4934-50ba-8046-7a96366d613b"
version = "4.1.3+3"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[XML2_jll]]
deps = ["Libdl", "Libiconv_jll", "Pkg", "Zlib_jll"]
git-tree-sha1 = "ecff6bff03b35d482ad5eb51276d6fc4c823cd39"
uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a"
version = "2.9.10+2"

[[Zlib_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "fdd89e5ab270ea0f2a0174bd9093e557d06d4bfa"
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.11+16"

[[Zstd_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "4de91f4313d9e88162d461e282fe3066ab3a3c09"
uuid = "3161d3a3-bdf6-5164-811a-617609db77b4"
version = "1.4.5+1"

[[bliss_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "2dd3966c5084f35af863e3cd5a98ee955f764d9f"
uuid = "508c9074-7a14-5c94-9582-3d4bc1871065"
version = "0.73.0+0"

[[boost_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "4135c43c414bc32041148999f707f88544d810f2"
uuid = "28df3c45-c428-5900-9ff8-a3135698ca75"
version = "1.71.0+2"

[[cddlib_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "877efde5e9e2416840b784a864671aebaaad481e"
uuid = "f07e07eb-5685-515a-97c8-3014f6152feb"
version = "0.94.10+0"

[[lib4ti2_jll]]
deps = ["GLPK_jll", "GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "764d2788b260b3d655e9030df0eab01ac3711cc5"
uuid = "1493ae25-0f90-5c0e-a06c-8c5077d6d66f"
version = "1.6.9+1"

[[libcxxwrap_julia_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "1b2520ea0c1d5cbc12e8a97c15427133d726f743"
uuid = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
version = "0.8.0+0"

[[libpolymake_julia_jll]]
deps = ["CompilerSupportLibraries_jll", "Libdl", "Pkg", "libcxxwrap_julia_jll", "polymake_jll"]
git-tree-sha1 = "a244c575533cd04c3ad05ad8e998cb873edb1fdc"
uuid = "4d8266f6-2b3b-57e3-ad7a-d431eaaac945"
version = "0.1.2+0"

[[libsingular_julia_jll]]
deps = ["CompilerSupportLibraries_jll", "Libdl", "Pkg", "Singular_jll", "libcxxwrap_julia_jll"]
git-tree-sha1 = "b5eb76d0dbf5e43c27f4b1747096dd56b010efb3"
uuid = "ae4fbd8f-ecdb-54f8-bbce-35570499b30e"
version = "0.2.0+0"

[[lrslib_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "6952c85611d3064f2743bcc5b88563b64098509d"
uuid = "3873f7d0-7b7c-52c3-bdf4-8ab39b8f337a"
version = "0.1.0+1"

[[nauty_jll]]
deps = ["GMP_jll", "Libdl", "Pkg"]
git-tree-sha1 = "2f41f884c7021fab26c718ca7eeea78122304d3a"
uuid = "55c6dc9b-343a-50ca-8ff2-b71adb3733d5"
version = "2.6.12+0"

[[normaliz_jll]]
deps = ["CompilerSupportLibraries_jll", "FLINT_jll", "GMP_jll", "Libdl", "Pkg", "nauty_jll"]
git-tree-sha1 = "4f5482ed648d73fe8cfd9f92524fb61fd0e156b7"
uuid = "6690c6e9-4e12-53b8-b8fd-4bffaef8839f"
version = "3.8.5+0"

[[polymake_jll]]
deps = ["CompilerSupportLibraries_jll", "FLINT_jll", "GMP_jll", "Libdl", "MPFR_jll", "PPL_jll", "Perl_jll", "Pkg", "bliss_jll", "boost_jll", "cddlib_jll", "lrslib_jll", "normaliz_jll"]
git-tree-sha1 = "7603cc8a65bfd5cf9bc83a6b565ee03d68ec0396"
uuid = "7c209550-9012-526c-9264-55ba7a78ba2c"
version = "4.1.0+2"

[[snappy_jll]]
deps = ["LZO_jll", "Libdl", "Pkg", "Zlib_jll"]
git-tree-sha1 = "c1195c341330c685d68aa2519fd3935c5bdefc5d"
uuid = "fe1e1685-f7be-5f59-ac9f-4ca204017dfd"
version = "1.1.8+0"
